name: Deploy to o2switch
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install lftp
        run: sudo apt-get install -y lftp
      - name: FTP Deploy
        run: |
          lftp -c "
            set ftp:ssl-allow no;
            open -u wujo2132,${{ secrets.FTP_PASSWORD }} ftp.wujo2132.odns.fr;
            mirror -R --delete --verbose site/ /public_html/
          "
